version: "3.8"

services:
  mongodb_server:
    image: mongo:4.4
    command: mongod --serviceExecutor adaptive
    ports:
      - '1231:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin_user
      - MONGO_INITDB_ROOT_PASSWORD=admin_pass

  redis:
    image: 'redis:4-alpine'
    command: redis-server --requirepass 102030
    ports:
      - '1230:6379'

  contact_list_api:
    image: contact_list_api:latest
    links:
      - "mongodb_server:mongodb_server"
      - "redis:redis"
    build: .
    ports:
      - '8888:5556'
    environment:
      - MONGO_HOST=mongodb_server
      - MONGO_PORT=27017
      - MONGO_USER=admin_user
      - MONGO_PASS=admin_pass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=102030
      - REDIS_DB=0
      - ROUTERS_PREFIX=/g3
